framework:
    default_locale: 'fr'
    translator:
        fallbacks: ['fr']

#framework:
    #default_locale: '%locale%'
    #translator:
        #default_path: '%kernel.project_dir%/translations'
        #fallbacks:
            #- '%locale%'
