twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        article_repository: '@App\Repository\ArticleRepository'
        categorie_repository: '@App\Repository\CategorieRepository'
    form_themes:
        - 'bootstrap_4_layout.html.twig'    
    
