easy_admin:
  #site_name: 'Elan<em style="font-size: 80%;">ature</em>'
  site_name: '<img src="/img/logo.png" width="150" height="50" float="left"/>'
  user:
    display_name: false
    display_avatar: true
      # this will look for getFullName(), isFullName(), ..., and 'fullName' property
      #name_property_path: 'fullName'
      #avatar_property_path: 'gravatar'