easy_admin:
  entities:
    Membre:
      class: App\Entity\Membre
  design:
    brand_color: '#AFBD8E'
    assets:
      css:
        # ...
        - 'bundles/easyadmin/bootstrap-all.css'
      js:
        - 'bundles/easyadmin/bootstrap-all.js'

    menu:
      - label: 'Dashboard'
        icon: 'tachometer-alt'
        children:
          - { label: 'Public Homepage', url: 'http://example.com' }
          - { label: 'Search', url: 'https://google.com' }
          - {entity: 'Category', icon: 'tags', label: 'Categories', css_class: 'menu--user', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Categorie' }}
          - {entity: 'Article', icon: 'shopping-bag', label: 'Articles', css_class: 'menu--product text-bold text-center', default: true }
          - {entity: 'Commande', icon: 'shopping-cart', label: 'Commandes', css_class: 'default'}
          - {entity: 'Membre', icon: 'users', label: 'Membres', children: ['admin', 'clients']}



