easy_admin:
  entities:
    Article:
      class: App\Entity\Article
      #templates:
        #edit: 'admin/article/edit.html.twig'
      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
